### ISSUE TITLE
Generate enums that appear only in parameters

### ISSUE THREAD

**Issue by LukaHorvat** [LeapYear/graphql-client#58]
If I had a schema that included an enum like

```graphql
enum MyEnum {
    A
    B
    C
}
```

and then a query like

```grapql
query MyQuery($param: MyEnum) {
    ...some query using $param
}
```

it currently generates code that doesn't compile because it mentions the `MyEnum` type in the query parameters, but it doesn't actually generate the enum's definition.

**Comment by brandon-leapyear** [comment]
Released as graphql-client-1.1.1
